### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
also note that the example show a compilation warning in platformio:

```
src/main.cpp:97:7: warning: "/*" within comment [-Wcomment]
    *  /* Enable or disable latch. If latch is enabled the alarm pin will be active until the
       ^
```

**Comment by thijstriemstra** [comment]
And here's also a suggestion for simplifying the example(s):

```cpp
float readChannel(ADS1115_MUX channel) {
  float voltage = 0.0;
  adc.setCompareChannels(channel);
  adc.startSingleMeasurement();
  while(adc.isBusy()){}
  voltage = adc.getResult_V(); // alternative: getResult_mV for Millivolt
  return voltage;
}

void loop() {
  float voltage = 0.0;

  Serial.print("Channel: [0] ");
  voltage = readChannel(ADS1115_COMP_0_GND);
  Serial.print(voltage);

  Serial.print(", [1] ");
  voltage = readChannel(ADS1115_COMP_1_GND);
  Serial.print(voltage);
  
  Serial.print(", [2] ");
  voltage = readChannel(ADS1115_COMP_2_GND);
  Serial.print(voltage);

  Serial.print(", [3] ");
  voltage = readChannel(ADS1115_COMP_3_GND);
  Serial.println(voltage);

  //delay(1000);
}
```

**Comment by wollewald** [comment]
I have implemented all recommendations. Had the same typos in the other examples. Thanks again.

**Comment by thijstriemstra** [comment]
Ah too bad I didn't become a contributor to the project.

**Comment by wollewald** [comment]
I am sorry, that is related with fact that I have no experience yet with contributions. I have been very much on my own yet on Github. I am so thankful for your contribution. How can I make you a contributor?

 

Von: Thijs Triemstra <notifications@github.com> 
Gesendet: Sonntag, 26. Juli 2020 13:20
An: wollewald/ADS1115_WE <ADS1115_WE@noreply.github.com>
Cc: Wolfgang (Wolle) Ewald <wolfgang.ewald@wolles-elektronikkiste.de>; State change <state_change@noreply.github.com>
Betreff: Re: [wollewald/ADS1115_WE] fix typos (#2)

 

Ah too bad I didn't become a contributor to the project.

**Comment by thijstriemstra** [comment]
> How can I make you a contributor?

Sorry, I didn't know that. I would've expected you to merge this pull request and then make additional changes. If you copy my changes git(hub) won't record any of my contributions. I didn't spent much time on the changes but still, it's considered bad form to copy changes vs. trying to merge them. Now that you made your own changes this pull request is not needed anymore and making me a contributor requires me to make another contribution. I will. Thanks for your hard work!

**Comment by wollewald** [comment]
Sh...! Sorry again, at least I have learned something...

**Pull request closed without merging**
